#pragma once

#ifndef HAL_DEBUG_DEFAULT_BAUD
#define HAL_DEBUG_DEFAULT_BAUD 115200u
#endif

#define HAL_ENABLE_HTTP_FILES

#ifndef HAL_HTTP_SERVER_REQUEST_BUFFER_SIZE
#define HAL_HTTP_SERVER_REQUEST_BUFFER_SIZE 2048u
#endif

#ifndef HAL_HTTP_SERVER_RESPONSE_BUFFER_SIZE
#define HAL_HTTP_SERVER_RESPONSE_BUFFER_SIZE 2048u
#endif
