name=JaszczurHAL
version=1.4.0
author=jaszczurtd
sentence=Hardware Abstraction Layer for embedded projects
paragraph=HAL with hardware impl (RP2040/Arduino) and PC mock for unit testing.
category=Other
url=https://github.com/jaszczurtd/JaszczurHAL
architectures=rp2040
includes=JaszczurHAL.h
