// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// jh_swserial_rx //
// -------------- //

#define jh_swserial_rx_wrap_target 0
#define jh_swserial_rx_wrap 8
#define jh_swserial_rx_pio_version 0

static const uint16_t jh_swserial_rx_program_instructions[] = {
    //     .wrap_target
    0x2020, //  0: wait   0 pin, 0
    0xaa22, //  1: mov    x, y                   [10]
    0x4001, //  2: in     pins, 1
    0x0642, //  3: jmp    x--, 2                 [6]
    0x00c8, //  4: jmp    pin, 8
    0x20a0, //  5: wait   1 pin, 0
    0xa0c3, //  6: mov    isr, null
    0x0000, //  7: jmp    0
    0x8020, //  8: push   block
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program jh_swserial_rx_program = {
    .instructions = jh_swserial_rx_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = jh_swserial_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config
jh_swserial_rx_program_get_default_config(uint offset) {
  pio_sm_config c = pio_get_default_sm_config();
  sm_config_set_wrap(&c, offset + jh_swserial_rx_wrap_target,
                     offset + jh_swserial_rx_wrap);
  return c;
}
#endif

// -------------- //
// jh_swserial_tx //
// -------------- //

#define jh_swserial_tx_wrap_target 0
#define jh_swserial_tx_wrap 3
#define jh_swserial_tx_pio_version 0

static const uint16_t jh_swserial_tx_program_instructions[] = {
    //     .wrap_target
    0x98a0, //  0: pull   block           side 1
    0xb722, //  1: mov    x, y            side 0 [7]
    0x6001, //  2: out    pins, 1
    0x0642, //  3: jmp    x--, 2                 [6]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program jh_swserial_tx_program = {
    .instructions = jh_swserial_tx_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = jh_swserial_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config
jh_swserial_tx_program_get_default_config(uint offset) {
  pio_sm_config c = pio_get_default_sm_config();
  sm_config_set_wrap(&c, offset + jh_swserial_tx_wrap_target,
                     offset + jh_swserial_tx_wrap);
  sm_config_set_sideset(&c, 2, true, false);
  return c;
}
#endif
