#pragma once

/* ESP32-S3 values. */
#define SOC_GPIO_PIN_COUNT 49
#define SOC_LEDC_TIMER_NUM 4
#define SOC_LEDC_CHANNEL_NUM 8
#define SOC_LEDC_TIMER_BIT_WIDTH 14
#define SOC_ADC_DIGI_RESULT_BYTES 4
#define SOC_ADC_CHANNEL_NUM(unit) 10
#define SOC_ADC_DIGI_MAX_BITWIDTH 12
#define SOC_ADC_SAMPLE_FREQ_THRES_HIGH 83333
#define SOC_ADC_SAMPLE_FREQ_THRES_LOW 611
