#ifndef JASZCZURHAL_BTSTACK_CONFIG_H
#define JASZCZURHAL_BTSTACK_CONFIG_H

#include "hal/core/hal_project_config_hook.h"

#if defined(JH_BLUETOOTH_CLASSIC_HID_PROBE) &&                                 \
    (defined(JH_BLUETOOTH_STAGE1_PROBE) || defined(JH_BLUETOOTH_PUBLIC_BLE) || \
     defined(JH_BLUETOOTH_PUBLIC_HID_HOST))
#error "Classic HID probe cannot be combined with a BLE mode"
#endif

#if defined(JH_BLUETOOTH_CLASSIC_HID_PROBE) ||                                 \
    defined(JH_BLUETOOTH_PUBLIC_HID_HOST)
#define MAX_NR_HID_HOST_CONNECTIONS 1
#endif

#if defined(JH_BLUETOOTH_PUBLIC_A2DP_SINK)
#define MAX_NR_AVDTP_CONNECTIONS 1
#define MAX_NR_AVDTP_STREAM_ENDPOINTS 1
#if defined(JH_BLUETOOTH_PUBLIC_AVRCP_TARGET)
#define MAX_NR_AVRCP_CONNECTIONS 2
#define MAX_NR_SERVICE_RECORD_ITEMS 2
#else
#define MAX_NR_SERVICE_RECORD_ITEMS 1
#endif
#endif

#if defined(JH_BLUETOOTH_PUBLIC_A2DP_SINK) &&                                  \
    defined(JH_BLUETOOTH_PUBLIC_HID_HOST) && defined(JH_BLUETOOTH_PUBLIC_BLE)
#define ENABLE_LE_PERIPHERAL
#define ENABLE_SOFTWARE_AES128
#if defined(JH_BLUETOOTH_PUBLIC_AVRCP_TARGET)
#define MAX_NR_L2CAP_CHANNELS 8
#define MAX_NR_L2CAP_SERVICES 4
#else
#define MAX_NR_L2CAP_CHANNELS 7
#define MAX_NR_L2CAP_SERVICES 3
#endif
#define MAX_NR_HCI_CONNECTIONS 2
#elif defined(JH_BLUETOOTH_PUBLIC_A2DP_SINK) &&                                \
    defined(JH_BLUETOOTH_PUBLIC_HID_HOST)
#if defined(JH_BLUETOOTH_PUBLIC_AVRCP_TARGET)
#define MAX_NR_L2CAP_CHANNELS 6
#define MAX_NR_L2CAP_SERVICES 4
#else
#define MAX_NR_L2CAP_CHANNELS 5
#define MAX_NR_L2CAP_SERVICES 3
#endif
#define MAX_NR_HCI_CONNECTIONS 1
#elif defined(JH_BLUETOOTH_PUBLIC_A2DP_SINK) && defined(JH_BLUETOOTH_PUBLIC_BLE)
#define ENABLE_LE_PERIPHERAL
#define ENABLE_SOFTWARE_AES128
#if defined(JH_BLUETOOTH_PUBLIC_AVRCP_TARGET)
#define MAX_NR_L2CAP_CHANNELS 6
#define MAX_NR_L2CAP_SERVICES 4
#else
#define MAX_NR_L2CAP_CHANNELS 5
#define MAX_NR_L2CAP_SERVICES 3
#endif
#define MAX_NR_HCI_CONNECTIONS 2
#elif defined(JH_BLUETOOTH_PUBLIC_A2DP_SINK)
#if defined(JH_BLUETOOTH_PUBLIC_AVRCP_TARGET)
#define MAX_NR_L2CAP_CHANNELS 4
#define MAX_NR_L2CAP_SERVICES 3
#else
#define MAX_NR_L2CAP_CHANNELS 3
#define MAX_NR_L2CAP_SERVICES 2
#endif
#define MAX_NR_HCI_CONNECTIONS 1
#endif

#if defined(JH_BLUETOOTH_CLASSIC_HID_DEVICE_FIXTURE)
#define MAX_NR_BTSTACK_LINK_KEY_DB_MEMORY_ENTRIES 1
#define MAX_NR_SERVICE_RECORD_ITEMS 1
#elif defined(JH_BLUETOOTH_CLASSIC_HID_PROBE)
#define MAX_NR_BTSTACK_LINK_KEY_DB_MEMORY_ENTRIES 1
#elif defined(JH_BLUETOOTH_PUBLIC_CLASSIC) ||                                  \
    defined(JH_BLUETOOTH_PUBLIC_HID_HOST)
#ifndef HAL_BLUETOOTH_CLASSIC_MAX_PEERS
#define HAL_BLUETOOTH_CLASSIC_MAX_PEERS 4u
#endif
#define MAX_NR_BTSTACK_LINK_KEY_DB_MEMORY_ENTRIES                              \
  HAL_BLUETOOTH_CLASSIC_MAX_PEERS
#endif

#if !defined(JH_BLUETOOTH_PUBLIC_A2DP_SINK)
#if defined(JH_BLUETOOTH_CLASSIC_HID_DEVICE_FIXTURE)
#define MAX_NR_L2CAP_CHANNELS 3
#define MAX_NR_L2CAP_SERVICES 3
#define MAX_NR_HCI_CONNECTIONS 1
#elif defined(JH_BLUETOOTH_PUBLIC_HID_HOST) && defined(JH_BLUETOOTH_PUBLIC_BLE)
#define ENABLE_LE_PERIPHERAL
#define ENABLE_SOFTWARE_AES128
#define MAX_NR_L2CAP_CHANNELS 5
#define MAX_NR_L2CAP_SERVICES 3
#define MAX_NR_HCI_CONNECTIONS 2
#elif defined(JH_BLUETOOTH_CLASSIC_HID_PROBE) ||                               \
    defined(JH_BLUETOOTH_PUBLIC_HID_HOST)
#define MAX_NR_L2CAP_CHANNELS 3
#define MAX_NR_L2CAP_SERVICES 2
#define MAX_NR_HCI_CONNECTIONS 1
#elif defined(JH_BLUETOOTH_PUBLIC_CLASSIC) && defined(JH_BLUETOOTH_PUBLIC_BLE)
#define ENABLE_LE_PERIPHERAL
#define ENABLE_SOFTWARE_AES128
#define MAX_NR_L2CAP_CHANNELS 2
#define MAX_NR_L2CAP_SERVICES 1
#define MAX_NR_HCI_CONNECTIONS 2
#elif defined(JH_BLUETOOTH_PUBLIC_CLASSIC)
#define MAX_NR_L2CAP_CHANNELS 2
#define MAX_NR_L2CAP_SERVICES 1
#define MAX_NR_HCI_CONNECTIONS 1
#else
/* BLE Peripheral sizing validated by the hardware gates. */
#define ENABLE_LE_PERIPHERAL
#define ENABLE_SOFTWARE_AES128
#define MAX_NR_L2CAP_CHANNELS 2
#define MAX_NR_L2CAP_SERVICES 1
#define MAX_NR_HCI_CONNECTIONS 1
#endif
#endif

#define HCI_OUTGOING_PRE_BUFFER_SIZE 4
#define HCI_ACL_PAYLOAD_SIZE (1024 + 4)
#define HCI_ACL_CHUNK_SIZE_ALIGNMENT 4

#define MAX_NR_GATT_CLIENTS 0
#define MAX_NR_SM_LOOKUP_ENTRIES 1
#define MAX_NR_WHITELIST_ENTRIES 1
#define MAX_NR_LE_DEVICE_DB_ENTRIES 1
#define MAX_ATT_DB_SIZE 512

/* The shared CYW43 ring is small. Bound host/controller buffering so BLE
 * cannot starve Wi-Fi while the two protocols share gSPI. */
#define MAX_NR_CONTROLLER_ACL_BUFFERS 3
#define ENABLE_HCI_CONTROLLER_TO_HOST_FLOW_CONTROL
#define HCI_HOST_ACL_PACKET_LEN 1024
#define HCI_HOST_ACL_PACKET_NUM 3
#define HCI_HOST_SCO_PACKET_LEN 0
#define HCI_HOST_SCO_PACKET_NUM 0

#define HAVE_EMBEDDED_TIME_MS
#define HCI_RESET_RESEND_TIMEOUT_MS 1000

#endif
