#!/usr/bin/env python3
"""Generate the C view of the default values of the HAL component types.

The JSON types in config/hardware/bindings/ are the only source of device
defaults. The generated header holds:
- JH_ENUM_<TYPE>_<PROPERTY>_<VALUE>: the position of each string enum value,
  so C code can static_assert that a HAL enum keeps the same order;
- JH_DEFAULT_<TYPE>_<PROPERTY>: the default of a property;
- JH_DEFAULT_<MODULE>_<CHILD>_<PROPERTY>: the default of a child property
  after the values the module sets for that child.
HAL helpers read these macros instead of keeping a second table.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import Any

from codegen_support import check_generated_outputs, write_generated_outputs
from hardware_literals import LiteralError, c_literal, macro_token
import hardware_model
from repository_layout import DEVICE_DEFAULTS_HEADER_OUTPUT as OUTPUT

REPO_ROOT = Path(__file__).resolve().parents[1]


class DefaultsError(ValueError):
    """A default the header cannot express."""


def is_string_enum(definition: dict[str, Any]) -> bool:
    return definition["cType"] == "string" and "enum" in definition


def enum_macro(compatible: str, prop: str, value: str) -> str:
    return f"JH_ENUM_{macro_token(compatible)}_{macro_token(prop)}_{macro_token(value)}"


def render(catalogue: hardware_model.Catalogue) -> str:
    """The header text; a macro produced twice fails instead of being renamed."""
    lines = ["#pragma once",
             "/* Generated by generate_device_defaults.py from config/hardware/bindings;",
             " * do not edit. */"]
    origins: dict[str, str] = {}

    def define(name: str, value: str, origin: str) -> None:
        if name in origins:
            raise DefaultsError(f"{name} is produced by {origins[name]} and {origin}")
        origins[name] = origin
        lines.append(f"#define {name} {value}")

    def emit_defaults(prefix: str, compatible: str, values: dict[str, Any], origin: str) -> None:
        properties = catalogue.bindings[compatible].data.get("properties", {})
        for prop, value in sorted(values.items()):
            definition = properties[prop]
            try:
                literal = (enum_macro(compatible, prop, value) if is_string_enum(definition)
                           else c_literal(definition["cType"], value))
            except LiteralError as error:
                raise DefaultsError(f"{origin}.{prop}: {error}") from error
            define(f"{prefix}_{macro_token(prop)}", literal, f"{origin}.{prop}")

    for compatible, binding in sorted(catalogue.bindings.items()):
        enums = [(prop, d) for prop, d in sorted(binding.data.get("properties", {}).items())
                 if is_string_enum(d)]
        if enums:
            lines.append("")
            lines.append(f"/* {compatible}: enum positions */")
        for prop, definition in enums:
            for index, member in enumerate(definition["enum"]):
                define(enum_macro(compatible, prop, member), f"{index}U", f"{compatible}.{prop}")

    def defaults_of(compatible: str) -> dict[str, Any]:
        properties = catalogue.bindings[compatible].data.get("properties", {})
        return {name: d["default"] for name, d in properties.items() if "default" in d}

    for compatible, binding in sorted(catalogue.bindings.items()):
        prefix = f"JH_DEFAULT_{macro_token(compatible)}"
        groups = [(prefix, compatible, defaults_of(compatible), compatible)]
        for child_name, child in sorted(binding.data.get("children", {}).items()):
            groups.append((f"{prefix}_{macro_token(child_name)}", child["compatible"],
                           {**defaults_of(child["compatible"]), **child.get("properties", {})},
                           f"{compatible} child {child_name}"))
        if not any(values for _, _, values, _ in groups):
            continue
        lines.append("")
        lines.append(f"/* {compatible} */")
        for group_prefix, value_type, values, origin in groups:
            emit_defaults(group_prefix, value_type, values, origin)
    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="refresh the generated header")
    mode.add_argument("--check", action="store_true", help="fail when the header is stale")
    parser.add_argument("--bindings", type=Path, default=hardware_model.HAL_BINDINGS,
                        help="directory of HAL types (default: config/hardware/bindings)")
    parser.add_argument("--output-root", type=Path, default=REPO_ROOT,
                        help="root the header path is relative to (default: repository)")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        catalogue = hardware_model.load_hal_catalogue(args.bindings)
        hardware_model.check_catalogue(catalogue, hardware_model.hal_features(),
                                       hardware_model.board_capabilities())
        outputs = {OUTPUT: render(catalogue)}
        if args.write:
            write_generated_outputs(args.output_root, outputs, artifact_kind="device defaults",
                                    error_type=DefaultsError)
            return 0
        return 0 if check_generated_outputs(args.output_root, outputs,
                                            artifact_kind="device defaults",
                                            error_type=DefaultsError, diff_limit=40) else 1
    except (hardware_model.HardwareError, DefaultsError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
