#pragma once

#define HAL_ENABLE_EEPROM
#define HAL_ENABLE_KV
#define HAL_ENABLE_ADC_SCAN
#undef HAL_EEPROM_TYPE
#define HAL_EEPROM_TYPE EEPROM_TYPE_FLASH

#ifndef HAL_DEBUG_DEFAULT_BAUD
#define HAL_DEBUG_DEFAULT_BAUD 115200u
#endif
