#pragma once

#define EXCCAUSE_ILLEGAL 0
#define EXCCAUSE_INSTR_ERROR 2
#define EXCCAUSE_LOAD_STORE_ERROR 3
#define EXCCAUSE_DIVIDE_BY_ZERO 6
#define EXCCAUSE_PRIVILEGED 8
#define EXCCAUSE_UNALIGNED 9
#define EXCCAUSE_INSTR_DATA_ERROR 12
#define EXCCAUSE_LOAD_STORE_DATA_ERROR 13
#define EXCCAUSE_INSTR_ADDR_ERROR 14
#define EXCCAUSE_LOAD_STORE_ADDR_ERROR 15
#define EXCCAUSE_ITLB_MULTIHIT 17
#define EXCCAUSE_INSTR_RING 18
#define EXCCAUSE_INSTR_PROHIBITED 20
#define EXCCAUSE_DTLB_MULTIHIT 25
#define EXCCAUSE_LOAD_STORE_RING 26
#define EXCCAUSE_LOAD_PROHIBITED 28
#define EXCCAUSE_STORE_PROHIBITED 29
