# ─────────────────────────────────────────────────────────────────────────────
# JaszczurHAL rp2040 firmware recipe (arduino-cli).
#
# Included by cmake/jh_firmware_project after project(... NONE). Generalized from
# the VS Code project generator's proven template: generate a minimal sketch that
# includes <JaszczurHAL.h> (which wires setup/loop -> app_start/app_task0/
# app_task1), symlink the client project's sources into the sketch, compile with
# arduino-cli, and expose the canonical firmware* targets.
#
# Inputs (set by the dispatcher / manifest cache):
#   JH_ROOT, JH_PROJECT_DIR, JH_MODULE_NAME, ARDUINO_FQBN,
#   ARDUINO_UPLOAD_PORT, ARDUINO_VERBOSE, JH_USB_MANUFACTURER, JH_USB_PRODUCT,
#   JH_EXTRA_DEFINES, JH_PROJECT_SOURCES, JH_RP2040_FREERTOS
# ─────────────────────────────────────────────────────────────────────────────

include("${JH_ROOT}/cmake/jh_entry_adapter.cmake")
include("${JH_ROOT}/cmake/jh_cyw43_driver.cmake")
include("${JH_ROOT}/cmake/jh_bearssl.cmake")

if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_BUILD_TYPE MinSizeRel CACHE STRING
        "Build type (Debug, Release, RelWithDebInfo, MinSizeRel)" FORCE)
    set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS
        Debug Release RelWithDebInfo MinSizeRel)
endif()

set(ARDUINO_CLI "arduino-cli" CACHE STRING "arduino-cli executable")
set(ARDUINO_FQBN "rp2040:rp2040:rpipico" CACHE STRING "Arduino fully qualified board name")
set(ARDUINO_UPLOAD_PORT "" CACHE STRING "Arduino upload port")
set(ARDUINO_VERBOSE OFF CACHE BOOL "Enable verbose Arduino CLI output")
set(ARDUINO_LIBRARIES "" CACHE PATH "Extra Arduino libraries directory (--libraries)")
set(ARDUINO_WERROR OFF CACHE BOOL "Treat compiler warnings as errors (-Werror)")
set(JH_USB_MANUFACTURER "" CACHE STRING "USB manufacturer descriptor")
set(JH_USB_PRODUCT "" CACHE STRING "USB product descriptor")
set(JH_EXTRA_DEFINES "" CACHE STRING "Extra compile definitions for the firmware (';'-separated)")
set(JH_RP2040_BOARD_DEFINES "" CACHE STRING
    "Board-profile compile definitions for RP2040 (';'-separated)")
set(JH_RP2040_FREERTOS OFF CACHE BOOL "Build with arduino-pico FreeRTOS FQBN option")
set(JH_RP2040_EXTRA_LINK_FLAGS "" CACHE STRING
    "Additional RP2040 firmware linker flags")

function(_jh_rp2040_apply_freertos OUT_VAR FQBN)
    if(NOT JH_RP2040_FREERTOS)
        set(${OUT_VAR} "${FQBN}" PARENT_SCOPE)
        return()
    endif()

    set(_fqbn "${FQBN}")
    if("${_fqbn}" MATCHES "(^|[,:])os=")
        set(${OUT_VAR} "${_fqbn}" PARENT_SCOPE)
    elseif("${_fqbn}" MATCHES "^[^:]+:[^:]+:[^:]+$")
        set(${OUT_VAR} "${_fqbn}:os=freertos" PARENT_SCOPE)
    else()
        set(${OUT_VAR} "${_fqbn},os=freertos" PARENT_SCOPE)
    endif()
endfunction()

function(_jh_extract_define_value OUT_VAR KEY)
    set(_value "")
    foreach(_def IN LISTS ARGN)
        if("${_def}" MATCHES "^${KEY}=(.+)$")
            set(_value "${CMAKE_MATCH_1}")
        endif()
    endforeach()
    set(${OUT_VAR} "${_value}" PARENT_SCOPE)
endfunction()

function(_jh_rp2040_project_define_enabled OUT_VAR KEY)
    set(_enabled FALSE)
    foreach(_def IN LISTS ARGN)
        if("${_def}" STREQUAL "${KEY}" OR
           "${_def}" MATCHES "^${KEY}=([1-9][0-9]*|true|TRUE|on|ON)$")
            set(_enabled TRUE)
        endif()
    endforeach()
    if(EXISTS "${JH_PROJECT_DIR}/hal_project_config.h")
        file(STRINGS "${JH_PROJECT_DIR}/hal_project_config.h" _matching_lines
            REGEX "^[ \t]*#[ \t]*define[ \t]+${KEY}([ \t]+.*)?$")
        if(_matching_lines)
            set(_enabled TRUE)
        endif()
    endif()
    set(${OUT_VAR} ${_enabled} PARENT_SCOPE)
endfunction()

_jh_rp2040_apply_freertos(ARDUINO_FQBN "${ARDUINO_FQBN}")

set(APP_NAME "${JH_MODULE_NAME}")
set(SKETCH_DIR "${CMAKE_BINARY_DIR}/sketch/${APP_NAME}")
set(ARDUINO_BUILD_DIR "${CMAKE_BINARY_DIR}/arduino")
set(OUT_DIR "${JH_PROJECT_DIR}/.build")
set(FIRMWARE_ELF "${OUT_DIR}/firmware.elf")
set(FIRMWARE_BIN "${OUT_DIR}/firmware.bin")
set(FIRMWARE_UF2 "${OUT_DIR}/firmware.uf2")
set(FIRMWARE_MAP "${OUT_DIR}/firmware.map")

file(MAKE_DIRECTORY "${SKETCH_DIR}" "${ARDUINO_BUILD_DIR}" "${OUT_DIR}")

file(WRITE "${SKETCH_DIR}/${APP_NAME}.ino"
    "// Auto-generated by JaszczurHAL rp2040 recipe - do not edit or commit.\n"
    "// Application entry lives in the project sources via JaszczurHAL's\n"
    "// app_start / app_task0 / app_task1 contract.\n"
    "#include <JaszczurHAL.h>\n"
)

jh_resolve_project_sources(_project_files)
set(_jh_project_include_dirs "${JH_PROJECT_DIR}")
foreach(_src IN LISTS _project_files)
    get_filename_component(_src_dir "${_src}" DIRECTORY)
    list(APPEND _jh_project_include_dirs "${_src_dir}")
    get_filename_component(_file "${_src}" NAME)
    set(_dst "${SKETCH_DIR}/${_file}")
    file(REMOVE "${_dst}")
    file(CREATE_LINK "${_src}" "${_dst}" SYMBOLIC COPY_ON_ERROR)
endforeach()
list(REMOVE_DUPLICATES _jh_project_include_dirs)
set(_jh_project_include_flags "-I${SKETCH_DIR}")
foreach(_include_dir IN LISTS _jh_project_include_dirs)
    string(APPEND _jh_project_include_flags " -I${_include_dir}")
endforeach()

# Fiesta-convention projects (firmware_entry.h present): generate the canonical
# entry adapter straight into the sketch dir so arduino-cli compiles it, and turn
# on the library's setup()/loop() -> app_* bridge via HAL_PROVIDE_APP_ENTRY.
# Canonical-entry projects (e.g. vp37) have no firmware_entry.h and set the flags
# themselves in hal_project_config.h, so this leaves them byte-for-byte unchanged.
set(_entry_defs " -DHAL_PROVIDE_APP_ENTRY")
jh_generate_entry_adapter("${JH_PROJECT_DIR}" "${SKETCH_DIR}" _adapter _core1)
if(_adapter AND _core1)
    string(APPEND _entry_defs " -DHAL_ENABLE_APP_TASK1")
endif()
set(_extra_defines ${JH_RP2040_BOARD_DEFINES} ${JH_EXTRA_DEFINES})
if(JH_RP2040_FREERTOS)
    list(APPEND _extra_defines HAL_ENABLE_FREERTOS)
endif()
_jh_extract_define_value(_rp2040_stack_size HAL_RP2040_STACK_SIZE ${_extra_defines})
_jh_extract_define_value(_rp2040_core1_stack_size HAL_RP2040_CORE1_STACK_SIZE ${_extra_defines})
foreach(_def IN LISTS _extra_defines)
    string(APPEND _entry_defs " -D${_def}")
endforeach()

list(FIND _extra_defines HAL_CYW43_STACK_LWIP _jh_cyw43_lwip_index)
set(_jh_owned_network FALSE)
if(NOT _jh_cyw43_lwip_index EQUAL -1)
    set(_jh_owned_network TRUE)
    jh_cyw43_source_manifest(_jh_network_sources _jh_network_includes LWIP)
    set(_jh_network_source_dir "${SKETCH_DIR}/src/jh_owned_network")
    file(MAKE_DIRECTORY "${_jh_network_source_dir}")
    set(_jh_network_source_index 0)
    foreach(_jh_source IN LISTS _jh_network_sources)
        get_filename_component(_jh_name "${_jh_source}" NAME)
        string(REGEX REPLACE "\\.upstream$" "" _jh_name "${_jh_name}")
        set(_jh_generated
            "${_jh_network_source_dir}/${_jh_network_source_index}_${_jh_name}")
        if("${_jh_source}" MATCHES "/cyw43-driver/")
            set(_jh_cyw43_root
                "${JH_ROOT}/src/hal/impl/shared/drivers/cyw43-driver")
            file(WRITE "${_jh_generated}"
                "#define CYW43_CONFIG_FILE \"${_jh_cyw43_root}/cyw43_configport.h\"\n"
                "#define CYW43_CHIPSET_FIRMWARE_INCLUDE_FILE \"${_jh_cyw43_root}/vendor/firmware/w43439A0_7_95_49_00_combined.h\"\n"
                "#define CYW43_WIFI_NVRAM_INCLUDE_FILE \"${_jh_cyw43_root}/vendor/firmware/wifi_nvram_43439.h\"\n"
                "#include \"${_jh_source}\"\n")
        else()
            configure_file("${_jh_source}" "${_jh_generated}" COPYONLY)
        endif()
        math(EXPR _jh_network_source_index "${_jh_network_source_index} + 1")
    endforeach()
    foreach(_jh_include IN LISTS _jh_network_includes)
        if(NOT "${_jh_include}" MATCHES "/cyw43-driver")
            string(APPEND _jh_project_include_flags " -I${_jh_include}")
        endif()
    endforeach()
endif()
_jh_rp2040_project_define_enabled(
    _jh_owned_tls
    HAL_ENABLE_TLS
    ${_extra_defines})
if(_jh_owned_tls)
    jh_bearssl_source_manifest(_jh_bearssl_sources _jh_bearssl_includes)
    set(_jh_bearssl_source_dir "${SKETCH_DIR}/src/jh_owned_bearssl")
    file(MAKE_DIRECTORY "${_jh_bearssl_source_dir}")
    set(_jh_bearssl_source_index 0)
    foreach(_jh_source IN LISTS _jh_bearssl_sources)
        get_filename_component(_jh_name "${_jh_source}" NAME)
        string(REGEX REPLACE "\\.upstream$" "" _jh_name "${_jh_name}")
        set(_jh_generated
            "${_jh_bearssl_source_dir}/${_jh_bearssl_source_index}_${_jh_name}")
        file(WRITE "${_jh_generated}" "#include \"${_jh_source}\"\n")
        math(EXPR _jh_bearssl_source_index
            "${_jh_bearssl_source_index} + 1")
    endforeach()
    foreach(_jh_include IN LISTS _jh_bearssl_includes)
        string(APPEND _jh_project_include_flags " -I${_jh_include}")
    endforeach()
endif()
if(NOT "${_rp2040_stack_size}" STREQUAL "")
    string(APPEND _entry_defs " -DPICO_STACK_SIZE=${_rp2040_stack_size}")
endif()
if(NOT "${_rp2040_core1_stack_size}" STREQUAL "")
    string(APPEND _entry_defs " -DPICO_CORE1_STACK_SIZE=${_rp2040_core1_stack_size}")
endif()
if(ARDUINO_WERROR)
    string(APPEND _entry_defs " -Werror")
endif()

set(ARDUINO_COMMON_ARGS
    compile
    --fqbn "${ARDUINO_FQBN}"
    --build-path "${ARDUINO_BUILD_DIR}"
    --library "${JH_ROOT}"
    --build-property "compiler.cpp.extra_flags=${_jh_project_include_flags}${_entry_defs}"
    --build-property "compiler.c.extra_flags=${_jh_project_include_flags}${_entry_defs}"
    --warnings all
)
if(_jh_owned_network)
    # Arduino-Pico's link recipe always emits the quoted build.libpicow slot.
    # Point that mandatory slot at the already-required base runtime archive;
    # an empty value would turn the containing directory into a linker input.
    list(APPEND ARDUINO_COMMON_ARGS
        --build-property
        "compiler.wrap=\"@{runtime.platform.path}/lib/{build.chip}/platform_wrap.txt\" \"@${JH_ROOT}/cmake/rp2040_core_wrap_non_network.txt\""
        --build-property "compiler.netdefines="
        --build-property "build.libpicow=libpico.a"
        --build-property "build.libpicowdefs="
        --build-property "build.wificc="
    )
endif()
if(_jh_owned_tls)
    list(APPEND ARDUINO_COMMON_ARGS
        --build-property "compiler.libbearssl="
    )
endif()
if(JH_RP2040_EXTRA_LINK_FLAGS)
    list(APPEND ARDUINO_COMMON_ARGS
        --build-property
        "compiler.c.elf.extra_flags=${JH_RP2040_EXTRA_LINK_FLAGS}"
    )
endif()
if(ARDUINO_LIBRARIES)
    list(APPEND ARDUINO_COMMON_ARGS --libraries "${ARDUINO_LIBRARIES}")
endif()
if(JH_USB_MANUFACTURER AND JH_USB_PRODUCT)
    list(APPEND ARDUINO_COMMON_ARGS
        --build-property "build.usb_manufacturer=\"${JH_USB_MANUFACTURER}\""
        --build-property "build.usb_product=\"${JH_USB_PRODUCT}\""
    )
endif()
if(ARDUINO_VERBOSE)
    list(APPEND ARDUINO_COMMON_ARGS --verbose)
endif()

function(_jh_rp2040_target target_name)
    set(options DEBUG UPLOAD COMPILE_DB)
    cmake_parse_arguments(ARG "${options}" "" "" ${ARGN})

    set(_cmd "${ARDUINO_CLI}" ${ARDUINO_COMMON_ARGS})
    if(ARG_DEBUG OR CMAKE_BUILD_TYPE STREQUAL "Debug")
        list(APPEND _cmd --optimize-for-debug)
    elseif(CMAKE_BUILD_TYPE STREQUAL "MinSizeRel")
        list(APPEND _cmd --build-property "build.flags.optimize=-Os -DNDEBUG")
    elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
        list(APPEND _cmd --build-property "build.flags.optimize=-O3 -DNDEBUG")
    elseif(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
        list(APPEND _cmd --build-property "build.flags.optimize=-O2 -DNDEBUG")
    endif()
    if(ARG_COMPILE_DB)
        list(APPEND _cmd --only-compilation-database)
    endif()
    if(ARG_UPLOAD)
        list(APPEND _cmd --upload)
        if(ARDUINO_UPLOAD_PORT)
            list(APPEND _cmd --port "${ARDUINO_UPLOAD_PORT}")
        endif()
    endif()
    list(APPEND _cmd "${SKETCH_DIR}")

    add_custom_target("${target_name}"
        COMMAND ${_cmd}
        WORKING_DIRECTORY "${JH_PROJECT_DIR}"
        USES_TERMINAL
        VERBATIM
    )
    if(NOT ARG_COMPILE_DB)
        add_custom_command(TARGET "${target_name}" POST_BUILD
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${ARDUINO_BUILD_DIR}/${APP_NAME}.ino.elf" "${FIRMWARE_ELF}"
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${ARDUINO_BUILD_DIR}/${APP_NAME}.ino.bin" "${FIRMWARE_BIN}"
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${ARDUINO_BUILD_DIR}/${APP_NAME}.ino.uf2" "${FIRMWARE_UF2}"
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${ARDUINO_BUILD_DIR}/${APP_NAME}.ino.map" "${FIRMWARE_MAP}"
            VERBATIM
        )
    endif()
endfunction()

_jh_rp2040_target(firmware)
_jh_rp2040_target(firmware_debug DEBUG)
_jh_rp2040_target(firmware_upload UPLOAD)
_jh_rp2040_target(firmware_compile_db COMPILE_DB)

message(STATUS "jh-firmware[rp2040]: FQBN=${ARDUINO_FQBN} sketch=${SKETCH_DIR}")
