# ─────────────────────────────────────────────────────────────────────────────
# JaszczurHAL rp2040 firmware recipe (arduino-cli).
#
# Included by cmake/jh_firmware_project after project(... NONE). Generalized from
# the VS Code project generator's proven template: generate a minimal sketch that
# includes <JaszczurHAL.h> (which wires setup/loop -> app_start/app_task0/
# app_task1), symlink the client project's sources into the sketch, compile with
# arduino-cli, and expose the canonical firmware* targets.
#
# Inputs (set by the dispatcher / manifest cache):
#   JH_ROOT, JH_PROJECT_DIR, JH_MODULE_NAME, ARDUINO_FQBN,
#   ARDUINO_UPLOAD_PORT, ARDUINO_VERBOSE, JH_USB_MANUFACTURER, JH_USB_PRODUCT
# ─────────────────────────────────────────────────────────────────────────────

include("${JH_ROOT}/cmake/jh_entry_adapter.cmake")

set(ARDUINO_CLI "arduino-cli" CACHE STRING "arduino-cli executable")
set(ARDUINO_FQBN "rp2040:rp2040:rpipico" CACHE STRING "Arduino fully qualified board name")
set(ARDUINO_UPLOAD_PORT "" CACHE STRING "Arduino upload port")
set(ARDUINO_VERBOSE OFF CACHE BOOL "Enable verbose Arduino CLI output")
set(ARDUINO_LIBRARIES "" CACHE PATH "Extra Arduino libraries directory (--libraries)")
set(ARDUINO_WERROR OFF CACHE BOOL "Treat compiler warnings as errors (-Werror)")
set(JH_USB_MANUFACTURER "" CACHE STRING "USB manufacturer descriptor")
set(JH_USB_PRODUCT "" CACHE STRING "USB product descriptor")

set(APP_NAME "${JH_MODULE_NAME}")
set(SKETCH_DIR "${CMAKE_BINARY_DIR}/sketch/${APP_NAME}")
set(ARDUINO_BUILD_DIR "${JH_PROJECT_DIR}/.build/arduino")
set(OUT_DIR "${JH_PROJECT_DIR}/.build")
set(FIRMWARE_ELF "${OUT_DIR}/firmware.elf")
set(FIRMWARE_BIN "${OUT_DIR}/firmware.bin")
set(FIRMWARE_UF2 "${OUT_DIR}/firmware.uf2")
set(FIRMWARE_MAP "${OUT_DIR}/firmware.map")

file(MAKE_DIRECTORY "${SKETCH_DIR}" "${ARDUINO_BUILD_DIR}" "${OUT_DIR}")

file(WRITE "${SKETCH_DIR}/${APP_NAME}.ino"
    "// Auto-generated by JaszczurHAL rp2040 recipe - do not edit or commit.\n"
    "// Application entry lives in the project sources via JaszczurHAL's\n"
    "// app_start / app_task0 / app_task1 contract.\n"
    "#include <JaszczurHAL.h>\n"
)

file(GLOB _project_files CONFIGURE_DEPENDS
    "${JH_PROJECT_DIR}/*.c"
    "${JH_PROJECT_DIR}/*.cpp"
    "${JH_PROJECT_DIR}/*.h"
    "${JH_PROJECT_DIR}/*.hpp"
)
foreach(_src IN LISTS _project_files)
    get_filename_component(_file "${_src}" NAME)
    set(_dst "${SKETCH_DIR}/${_file}")
    file(REMOVE "${_dst}")
    file(CREATE_LINK "${_src}" "${_dst}" SYMBOLIC COPY_ON_ERROR)
endforeach()

# Fiesta-convention projects (firmware_entry.h present): generate the canonical
# entry adapter straight into the sketch dir so arduino-cli compiles it, and turn
# on the library's setup()/loop() -> app_* bridge via HAL_PROVIDE_APP_ENTRY.
# Canonical-entry projects (e.g. vp37) have no firmware_entry.h and set the flags
# themselves in hal_project_config.h, so this leaves them byte-for-byte unchanged.
set(_entry_defs "")
jh_generate_entry_adapter("${JH_PROJECT_DIR}" "${SKETCH_DIR}" _adapter _core1)
if(_adapter)
    set(_entry_defs " -DHAL_PROVIDE_APP_ENTRY")
    if(_core1)
        string(APPEND _entry_defs " -DHAL_ENABLE_APP_TASK1")
    endif()
endif()
if(ARDUINO_WERROR)
    string(APPEND _entry_defs " -Werror")
endif()

set(ARDUINO_COMMON_ARGS
    compile
    --fqbn "${ARDUINO_FQBN}"
    --build-path "${ARDUINO_BUILD_DIR}"
    --library "${JH_ROOT}"
    --build-property "compiler.cpp.extra_flags=-I${SKETCH_DIR} -I${JH_PROJECT_DIR}${_entry_defs}"
    --build-property "compiler.c.extra_flags=-I${SKETCH_DIR} -I${JH_PROJECT_DIR}${_entry_defs}"
    --warnings all
)
if(ARDUINO_LIBRARIES)
    list(APPEND ARDUINO_COMMON_ARGS --libraries "${ARDUINO_LIBRARIES}")
endif()
if(JH_USB_MANUFACTURER AND JH_USB_PRODUCT)
    list(APPEND ARDUINO_COMMON_ARGS
        --build-property "build.usb_manufacturer=\"${JH_USB_MANUFACTURER}\""
        --build-property "build.usb_product=\"${JH_USB_PRODUCT}\""
    )
endif()
if(ARDUINO_VERBOSE)
    list(APPEND ARDUINO_COMMON_ARGS --verbose)
endif()

function(_jh_rp2040_target target_name)
    set(options DEBUG UPLOAD COMPILE_DB)
    cmake_parse_arguments(ARG "${options}" "" "" ${ARGN})

    set(_cmd "${ARDUINO_CLI}" ${ARDUINO_COMMON_ARGS})
    if(ARG_DEBUG)
        list(APPEND _cmd --optimize-for-debug)
    endif()
    if(ARG_COMPILE_DB)
        list(APPEND _cmd --only-compilation-database)
    endif()
    if(ARG_UPLOAD)
        list(APPEND _cmd --upload)
        if(ARDUINO_UPLOAD_PORT)
            list(APPEND _cmd --port "${ARDUINO_UPLOAD_PORT}")
        endif()
    endif()
    list(APPEND _cmd "${SKETCH_DIR}")

    add_custom_target("${target_name}"
        COMMAND ${_cmd}
        WORKING_DIRECTORY "${JH_PROJECT_DIR}"
        USES_TERMINAL
        VERBATIM
    )
    if(NOT ARG_COMPILE_DB)
        add_custom_command(TARGET "${target_name}" POST_BUILD
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${ARDUINO_BUILD_DIR}/${APP_NAME}.ino.elf" "${FIRMWARE_ELF}"
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${ARDUINO_BUILD_DIR}/${APP_NAME}.ino.bin" "${FIRMWARE_BIN}"
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${ARDUINO_BUILD_DIR}/${APP_NAME}.ino.uf2" "${FIRMWARE_UF2}"
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${ARDUINO_BUILD_DIR}/${APP_NAME}.ino.map" "${FIRMWARE_MAP}"
            VERBATIM
        )
    endif()
endfunction()

_jh_rp2040_target(firmware)
_jh_rp2040_target(firmware_debug DEBUG)
_jh_rp2040_target(firmware_upload UPLOAD)
_jh_rp2040_target(firmware_compile_db COMPILE_DB)

message(STATUS "jh-firmware[rp2040]: FQBN=${ARDUINO_FQBN} sketch=${SKETCH_DIR}")
