# ─────────────────────────────────────────────────────────────────────────────
# Shared HAL-entry adapter generator (used by every target recipe).
#
# JaszczurHAL's entry contract is app_start / app_task0 / app_task1
# (see src/hal/core/hal_app.h). Projects that follow a different convention - notably
# the Fiesta initialization/looper convention, marked by a firmware_entry.h -
# get a small cross-target adapter generated in the build dir (never in the
# source tree) that bridges that convention onto the HAL entry. On
# RP, initialization1() must run on core 1; other backends retain their common
# app_start() initialization order. The library's hal_app_entry.cpp supplies
# main(), gated by HAL_PROVIDE_APP_ENTRY.
#
# jh_generate_entry_adapter(<project_dir> <out_dir> <out_adapter_var> <out_core1_var>)
#   - If <project_dir>/firmware_entry.h exists: writes the adapter to
#     <out_dir>/jh_hal_app_adapter.cpp, sets <out_adapter_var> to that path and
#     <out_core1_var> to TRUE/FALSE (from FIESTA_ENABLE_CORE1 in the header).
#   - Otherwise (direct-entry project): both output vars are left empty/FALSE.
# ─────────────────────────────────────────────────────────────────────────────

function(jh_validate_entry_adapter_features has_core1)
    if(NOT has_core1)
        return()
    endif()
    set(_resolved_features ${ARGN})
    list(FIND _resolved_features HAL_ENABLE_APP_TASK1 _app_task1_index)
    if(_app_task1_index EQUAL -1)
        message(FATAL_ERROR
            "[JH-CFG-PARITY] FIESTA_ENABLE_CORE1=1 requires "
            "HAL_ENABLE_APP_TASK1 in hal_project_config.h or the active "
            "feature inputs")
    endif()
endfunction()

function(jh_generate_entry_adapter project_dir out_dir out_adapter_var out_core1_var)
    set(${out_adapter_var} "" PARENT_SCOPE)
    set(${out_core1_var} FALSE PARENT_SCOPE)

    set(_entry_header "${project_dir}/firmware_entry.h")
    if(NOT EXISTS "${_entry_header}")
        return()
    endif()

    file(READ "${_entry_header}" _entry_txt)
    set(_core1 FALSE)
    if(_entry_txt MATCHES "define[ \t]+FIESTA_ENABLE_CORE1[ \t]+1")
        set(_core1 TRUE)
    endif()

    file(MAKE_DIRECTORY "${out_dir}")
    set(_adapter "${out_dir}/jh_hal_app_adapter.cpp")
    file(WRITE "${_adapter}" [==[
// Auto-generated by JaszczurHAL - do not edit or commit.
// Bridges the Fiesta initialization/looper convention onto the HAL
// app_start / app_task0 / app_task1 entry contract.
#include <hal/core/hal_app.h>
#include <hal/core/hal_target.h>
#include "firmware_entry.h"

extern "C" void app_start(void) {
    initialization();
#if defined(FIESTA_ENABLE_CORE1) && FIESTA_ENABLE_CORE1 && !HAL_TARGET_IS_RP
    initialization1();
#endif
}

extern "C" void app_task0(void) { looper(); }

#if defined(FIESTA_ENABLE_CORE1) && FIESTA_ENABLE_CORE1
extern "C" void app_task1(void) {
#if HAL_TARGET_IS_RP
    static bool initialized = false;
    if (!initialized) {
        initialization1();
        initialized = true;
    }
#endif
    looper1();
}
#endif
]==])

    set(${out_adapter_var} "${_adapter}" PARENT_SCOPE)
    set(${out_core1_var} ${_core1} PARENT_SCOPE)
endfunction()
