# ─────────────────────────────────────────────────────────────────────────────
# Shared canonical-entry adapter generator (used by every target recipe).
#
# JaszczurHAL's canonical entry contract is app_start / app_task0 / app_task1
# (see src/hal/hal_app.h). Projects that follow a different convention - notably
# the Fiesta initialization/looper convention, marked by a firmware_entry.h -
# get a small, target-UNAWARE adapter generated in the build dir (never in the
# source tree) that bridges that convention onto the canonical entry. The same
# adapter works for every backend: on RP2040/Arduino the library's
# hal_app_entry.cpp maps setup()/loop() -> app_*, and on STM32 the HAL provides
# main() -> app_*, both gated by HAL_PROVIDE_APP_ENTRY.
#
# jh_generate_entry_adapter(<project_dir> <out_dir> <out_adapter_var> <out_core1_var>)
#   - If <project_dir>/firmware_entry.h exists: writes the adapter to
#     <out_dir>/jh_hal_app_adapter.cpp, sets <out_adapter_var> to that path and
#     <out_core1_var> to TRUE/FALSE (from FIESTA_ENABLE_CORE1 in the header).
#   - Otherwise (canonical-entry project): both output vars are left empty/FALSE.
# ─────────────────────────────────────────────────────────────────────────────

function(jh_generate_entry_adapter project_dir out_dir out_adapter_var out_core1_var)
    set(${out_adapter_var} "" PARENT_SCOPE)
    set(${out_core1_var} FALSE PARENT_SCOPE)

    set(_entry_header "${project_dir}/firmware_entry.h")
    if(NOT EXISTS "${_entry_header}")
        return()
    endif()

    file(READ "${_entry_header}" _entry_txt)
    set(_core1 FALSE)
    if(_entry_txt MATCHES "define[ \t]+FIESTA_ENABLE_CORE1[ \t]+1")
        set(_core1 TRUE)
    endif()

    file(MAKE_DIRECTORY "${out_dir}")
    set(_adapter "${out_dir}/jh_hal_app_adapter.cpp")
    file(WRITE "${_adapter}" [==[
// Auto-generated by JaszczurHAL - do not edit or commit.
// Bridges the Fiesta initialization/looper convention onto the canonical
// app_start / app_task0 / app_task1 entry contract.
#include <hal/hal_app.h>
#include "firmware_entry.h"

extern "C" void app_start(void) {
    initialization();
#if defined(FIESTA_ENABLE_CORE1) && FIESTA_ENABLE_CORE1
    initialization1();
#endif
}

extern "C" void app_task0(void) { looper(); }

#if defined(FIESTA_ENABLE_CORE1) && FIESTA_ENABLE_CORE1
extern "C" void app_task1(void) { looper1(); }
#endif
]==])

    set(${out_adapter_var} "${_adapter}" PARENT_SCOPE)
    set(${out_core1_var} ${_core1} PARENT_SCOPE)
endfunction()
