include_guard(GLOBAL)

# Apply one host-warning policy across GNU-like and MSVC compilers.
# Pass ERRORS when warnings are part of the target's quality gate.
function(jh_host_warning_options OUT_VAR COMPILER_FAMILY)
    cmake_parse_arguments(JH_WARNINGS "ERRORS" "" "" ${ARGN})
    set(_options)
    if(COMPILER_FAMILY STREQUAL "MSVC")
        list(APPEND _options /W4 /permissive-)
        if(JH_WARNINGS_ERRORS)
            list(APPEND _options /WX)
        endif()
    elseif(COMPILER_FAMILY MATCHES "GNU|Clang")
        list(APPEND _options -Wall -Wextra)
        if(JH_WARNINGS_ERRORS)
            list(APPEND _options -Werror)
        endif()
    endif()
    set(${OUT_VAR} "${_options}" PARENT_SCOPE)
endfunction()

function(jh_enable_host_warnings TARGET)
    cmake_parse_arguments(JH_WARNINGS "ERRORS" "" "" ${ARGN})
    if(MSVC OR CMAKE_C_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC" OR
            CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
        set(_family MSVC)
    elseif(CMAKE_CXX_COMPILER_ID)
        set(_family "${CMAKE_CXX_COMPILER_ID}")
    else()
        set(_family "${CMAKE_C_COMPILER_ID}")
    endif()
    if(JH_WARNINGS_ERRORS)
        jh_host_warning_options(_options "${_family}" ERRORS)
    else()
        jh_host_warning_options(_options "${_family}")
    endif()
    if(_options)
        target_compile_options(${TARGET} PRIVATE ${_options})
    else()
        message(STATUS
            "Host warning policy has no strict mapping for "
            "C=${CMAKE_C_COMPILER_ID}, CXX=${CMAKE_CXX_COMPILER_ID}: ${TARGET}")
    endif()
endfunction()
