#!/usr/bin/env python3
"""Generate a standalone JaszczurHAL VS Code example firmware project."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path


DEFAULT_PROJECT_NAME = "jaszczurhal-vscode-example"
DEFAULT_MODULE = "example"
DEFAULT_FQBN = "rp2040:rp2040:rpipico"
DEFAULT_USB_MANUFACTURER = "Jaszczur"
DEFAULT_USB_PRODUCT = "Example Project"


GENERATED_FILES = (
    ".gitignore",
    "README.md",
    "CMakeLists.txt",
    "app.cpp",
    "hal_project_config.h",
    ".vscode/jaszczurhal.project.json",
    ".vscode/settings.json",
    ".vscode/tasks.json",
    ".vscode/launch.json",
    ".vscode/extensions.json",
    ".vscode/keybindings.reference.json",
)


def relpath(from_dir: Path, to_path: Path) -> str:
    return os.path.relpath(to_path.resolve(), start=from_dir.resolve()).replace(os.sep, "/")


def sanitize_module(value: str) -> str:
    module = re.sub(r"[^A-Za-z0-9_]+", "_", value.strip()).strip("_")
    if not module:
        module = DEFAULT_MODULE
    if module[0].isdigit():
        module = f"_{module}"
    return module


def identity_hint(value: str) -> str:
    hint = re.sub(r"[^A-Za-z0-9]+", "_", value.strip()).strip("_")
    return hint or DEFAULT_USB_PRODUCT


def render_template(template: str, values: dict[str, str]) -> str:
    for key, value in values.items():
        template = template.replace(f"@@{key}@@", value)
    return template


def json_text(data: dict) -> str:
    return json.dumps(data, indent=4, sort_keys=False) + "\n"


def ensure_writable_output(output_dir: Path, force: bool) -> None:
    if not output_dir.exists():
        return
    if not output_dir.is_dir():
        raise RuntimeError(f"output path exists and is not a directory: {output_dir}")
    if force:
        return
    try:
        next(output_dir.iterdir())
    except StopIteration:
        return
    raise RuntimeError(
        f"output directory is not empty: {output_dir}\n"
        "Use --force to overwrite files generated by this tool."
    )


def build_files(
    *,
    output_dir: Path,
    project_name: str,
    module: str,
    fqbn: str,
    usb_manufacturer: str,
    usb_product: str,
    by_id_hint: str,
) -> dict[str, str]:
    script_path = Path(__file__).resolve()
    jh_root = script_path.parents[2]
    vscode_dir = output_dir / ".vscode"
    values = {
        "PROJECT_NAME": project_name,
        "MODULE": module,
        "FQBN": fqbn,
        "USB_MANUFACTURER": usb_manufacturer,
        "USB_PRODUCT": usb_product,
        "BY_ID_HINT": by_id_hint,
        "JH_ROOT_REL": relpath(output_dir, jh_root),
        "JH_ENTRY_REL": relpath(output_dir, jh_root / "vscode" / "entry" / "jh-vscode"),
        "SCHEMA_REL": relpath(vscode_dir, jh_root / "vscode" / "schema" / "jh_vscode_project.schema.json"),
    }

    files: dict[str, str] = {
        ".gitignore": GITIGNORE_TEMPLATE,
        "README.md": render_template(README_TEMPLATE, values),
        "CMakeLists.txt": render_template(CMAKE_TEMPLATE, values),
        "app.cpp": render_template(APP_CPP_TEMPLATE, values),
        "hal_project_config.h": HAL_PROJECT_CONFIG_TEMPLATE,
        ".vscode/jaszczurhal.project.json": json_text(
            {
                "$schema": values["SCHEMA_REL"],
                "project": project_name,
                "module": module,
                "toolchain": "cmake",
                "fqbn": fqbn,
                "buildDir": "${project}/.build",
                "cmakeBuildDir": "${project}/.build/cmake",
                "identity": {
                    "enabled": True,
                    "usbManufacturer": usb_manufacturer,
                    "usbProduct": usb_product,
                    "byIdHint": by_id_hint,
                },
                "upload": {
                    "strategy": "serial",
                },
                "artifacts": {
                    "elf": "${buildDir}/firmware.elf",
                    "uf2": "${buildDir}/firmware.uf2",
                    "compileCommands": "${buildDir}/compile_commands_patched.json",
                },
            }
        ),
        ".vscode/settings.json": json_text(
            {
                "jaszczurhal.cliPath": "arduino-cli",
                "jaszczurhal.sketchbookPath": "",
                "jaszczurhal.buildDir": "${workspaceFolder}/.build",
                "jaszczurhal.verbose": False,
                "jaszczurhal.root": values["JH_ROOT_REL"],
                "jaszczurhal.vscodeEntry": values["JH_ENTRY_REL"],
                "C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools",
                "C_Cpp.default.compileCommands": "${workspaceFolder}/.build/compile_commands_patched.json",
                "cmake.sourceDirectory": "${workspaceFolder}",
                "cmake.buildDirectory": "${workspaceFolder}/.build/cmake",
            }
        ),
        ".vscode/tasks.json": render_template(TASKS_TEMPLATE, values),
        ".vscode/launch.json": render_template(LAUNCH_TEMPLATE, values),
        ".vscode/extensions.json": json_text(
            {
                "recommendations": [
                    "ms-vscode.cpptools",
                    "ms-vscode.cmake-tools",
                    "marus25.cortex-debug",
                ]
            }
        ),
        ".vscode/keybindings.reference.json": render_template(KEYBINDINGS_TEMPLATE, values),
    }
    return files


def write_files(output_dir: Path, files: dict[str, str], dry_run: bool) -> None:
    for rel, content in files.items():
        path = output_dir / rel
        if dry_run:
            print(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a standalone JaszczurHAL VS Code example firmware project."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path.cwd() / DEFAULT_PROJECT_NAME,
        help=f"Target project directory, default: ./{DEFAULT_PROJECT_NAME}",
    )
    parser.add_argument("--name", default=DEFAULT_PROJECT_NAME, help="Project name stored in the manifest.")
    parser.add_argument("--module", default=DEFAULT_MODULE, help="Firmware module/sketch name, default: example.")
    parser.add_argument("--fqbn", default=DEFAULT_FQBN, help=f"Arduino FQBN, default: {DEFAULT_FQBN}.")
    parser.add_argument(
        "--usb-manufacturer",
        default=DEFAULT_USB_MANUFACTURER,
        help=f"USB manufacturer descriptor, default: {DEFAULT_USB_MANUFACTURER}.",
    )
    parser.add_argument(
        "--usb-product",
        default=DEFAULT_USB_PRODUCT,
        help=f"USB product descriptor, default: {DEFAULT_USB_PRODUCT}.",
    )
    parser.add_argument(
        "--by-id-hint",
        default="",
        help="Substring expected in /dev/serial/by-id; defaults to the USB product with spaces as underscores.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite files generated by this tool in an existing directory.",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print generated file paths without writing them.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    output_dir = args.output.expanduser().resolve()
    module = sanitize_module(args.module)
    by_id_hint = args.by_id_hint.strip() or identity_hint(args.usb_product)

    try:
        ensure_writable_output(output_dir, args.force)
        files = build_files(
            output_dir=output_dir,
            project_name=args.name.strip() or DEFAULT_PROJECT_NAME,
            module=module,
            fqbn=args.fqbn.strip() or DEFAULT_FQBN,
            usb_manufacturer=args.usb_manufacturer.strip() or DEFAULT_USB_MANUFACTURER,
            usb_product=args.usb_product.strip() or DEFAULT_USB_PRODUCT,
            by_id_hint=by_id_hint,
        )
        write_files(output_dir, files, args.dry_run)
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if not args.dry_run:
        print(f"Generated JaszczurHAL VS Code example: {output_dir}")
        print(f"Run: {relpath(output_dir, Path(__file__).resolve().parents[2] / 'vscode' / 'entry' / 'jh-vscode')} build --project {output_dir}")
    return 0


GITIGNORE_TEMPLATE = """.build/
build/
.vscode/.jh-upload-in-progress
.vscode/c_cpp_properties.json
compile_commands.json
compile_commands_patched.json
*.elf
*.bin
*.uf2
*.map
"""


README_TEMPLATE = """# @@PROJECT_NAME@@

Standalone JaszczurHAL VS Code example project generated by
`libraries/JaszczurHAL/vscode/tools/create-vscode-example.py`.

The project demonstrates the current firmware workflow:

- CMake owns sketch generation under `.build/cmake/sketch/@@MODULE@@`.
- `jh-vscode` owns build, debug build, upload, UF2 upload, monitor, clean, and IntelliSense refresh.
- The firmware identity is `@@USB_MANUFACTURER@@ @@USB_PRODUCT@@`.
- Application code lives in `app.cpp` and uses `app_start` / `app_task0`.

## Build

```bash
@@JH_ENTRY_REL@@ build --project "$PWD"
@@JH_ENTRY_REL@@ build-debug --project "$PWD"
@@JH_ENTRY_REL@@ refresh-intellisense --project "$PWD"
```

## Flashing

Check visible serial ports and BOOTSEL candidates before flashing:

```bash
@@JH_ENTRY_REL@@ list-ports --project "$PWD"
```

Default serial upload is identity-guarded. After the board already runs this
example firmware, use:

```bash
@@JH_ENTRY_REL@@ upload --project "$PWD"
```

For the first flash of a blank board, either use BOOTSEL:

```bash
@@JH_ENTRY_REL@@ upload-uf2 --project "$PWD"
```

or make an explicit serial decision:

```bash
@@JH_ENTRY_REL@@ upload --project "$PWD" --port /dev/ttyACM0 --allow-unverified-port
```

The explicit-port path is intentionally manual because it can overwrite any
board connected on that port.
"""


CMAKE_TEMPLATE = """cmake_minimum_required(VERSION 3.20)

project(@@MODULE@@ NONE)

set(APP_NAME "@@MODULE@@")
set(ARDUINO_CLI "arduino-cli" CACHE STRING "arduino-cli executable")
set(ARDUINO_FQBN "@@FQBN@@" CACHE STRING "Arduino fully qualified board name")
set(ARDUINO_SKETCHBOOK "" CACHE PATH "Arduino sketchbook path")
set(ARDUINO_UPLOAD_PORT "" CACHE STRING "Arduino upload port")
set(ARDUINO_VERBOSE OFF CACHE BOOL "Enable verbose Arduino CLI output")
set(JH_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/@@JH_ROOT_REL@@" CACHE PATH "JaszczurHAL library root")
set(JH_USB_MANUFACTURER "" CACHE STRING "USB manufacturer descriptor")
set(JH_USB_PRODUCT "" CACHE STRING "USB product descriptor")

if(NOT EXISTS "${JH_ROOT}/library.properties")
    message(FATAL_ERROR "JaszczurHAL not found at JH_ROOT='${JH_ROOT}'")
endif()

set(SKETCH_DIR "${CMAKE_BINARY_DIR}/sketch/${APP_NAME}")
set(ARDUINO_BUILD_DIR "${CMAKE_CURRENT_SOURCE_DIR}/.build/arduino")
set(FIRMWARE_ELF "${CMAKE_CURRENT_SOURCE_DIR}/.build/firmware.elf")
set(FIRMWARE_BIN "${CMAKE_CURRENT_SOURCE_DIR}/.build/firmware.bin")
set(FIRMWARE_UF2 "${CMAKE_CURRENT_SOURCE_DIR}/.build/firmware.uf2")
set(FIRMWARE_MAP "${CMAKE_CURRENT_SOURCE_DIR}/.build/firmware.map")

file(MAKE_DIRECTORY "${SKETCH_DIR}" "${ARDUINO_BUILD_DIR}")

file(WRITE "${SKETCH_DIR}/${APP_NAME}.ino"
    "// Auto-generated by CMake - do not edit or commit.\\n"
    "// Real application entry lives in app.cpp via JaszczurHAL app_start/app_task0.\\n"
    "#include <JaszczurHAL.h>\\n"
)

file(GLOB JH_EXAMPLE_PROJECT_FILES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/*.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/*.h"
    "${CMAKE_CURRENT_SOURCE_DIR}/*.hpp"
)

foreach(_src IN LISTS JH_EXAMPLE_PROJECT_FILES)
    get_filename_component(_file "${_src}" NAME)
    set(_dst "${SKETCH_DIR}/${_file}")
    file(REMOVE "${_dst}")
    file(CREATE_LINK "${_src}" "${_dst}" SYMBOLIC COPY_ON_ERROR)
endforeach()

set(ARDUINO_LIBRARY_ARGS)
set(_sketchbook_libraries "")
set(_jh_in_sketchbook OFF)

if(ARDUINO_SKETCHBOOK)
    set(_sketchbook_libraries "${ARDUINO_SKETCHBOOK}/libraries")
    if(EXISTS "${_sketchbook_libraries}")
        list(APPEND ARDUINO_LIBRARY_ARGS --libraries "${_sketchbook_libraries}")
        if(EXISTS "${_sketchbook_libraries}/JaszczurHAL/library.properties")
            file(REAL_PATH "${JH_ROOT}" _jh_root_real)
            file(REAL_PATH "${_sketchbook_libraries}/JaszczurHAL" _jh_sketchbook_real)
            if(_jh_root_real STREQUAL _jh_sketchbook_real)
                set(_jh_in_sketchbook ON)
            endif()
        endif()
    endif()
endif()

if(NOT _jh_in_sketchbook)
    list(APPEND ARDUINO_LIBRARY_ARGS --library "${JH_ROOT}")
endif()

set(ARDUINO_COMMON_ARGS
    compile
    --fqbn "${ARDUINO_FQBN}"
    --build-path "${ARDUINO_BUILD_DIR}"
    ${ARDUINO_LIBRARY_ARGS}
    --build-property "compiler.cpp.extra_flags=-I${SKETCH_DIR} -I${CMAKE_CURRENT_SOURCE_DIR}"
    --build-property "compiler.c.extra_flags=-I${SKETCH_DIR} -I${CMAKE_CURRENT_SOURCE_DIR}"
    --warnings all
)

if(JH_USB_MANUFACTURER AND JH_USB_PRODUCT)
    list(APPEND ARDUINO_COMMON_ARGS
        --build-property "build.usb_manufacturer=\\"${JH_USB_MANUFACTURER}\\""
        --build-property "build.usb_product=\\"${JH_USB_PRODUCT}\\""
    )
endif()

if(ARDUINO_VERBOSE)
    list(APPEND ARDUINO_COMMON_ARGS --verbose)
endif()

function(add_arduino_compile_target target_name)
    set(options DEBUG UPLOAD COMPILE_DB)
    cmake_parse_arguments(ARG "${options}" "" "" ${ARGN})

    set(_cmd "${ARDUINO_CLI}" ${ARDUINO_COMMON_ARGS})

    if(ARG_DEBUG)
        list(APPEND _cmd --optimize-for-debug)
    endif()

    if(ARG_COMPILE_DB)
        list(APPEND _cmd --only-compilation-database)
    endif()

    if(ARG_UPLOAD)
        list(APPEND _cmd --upload)
        if(ARDUINO_UPLOAD_PORT)
            list(APPEND _cmd --port "${ARDUINO_UPLOAD_PORT}")
        endif()
    endif()

    list(APPEND _cmd "${SKETCH_DIR}")

    add_custom_target("${target_name}"
        COMMAND ${_cmd}
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        USES_TERMINAL
        VERBATIM
    )

    if(NOT ARG_COMPILE_DB)
        add_custom_command(TARGET "${target_name}" POST_BUILD
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different
                "${ARDUINO_BUILD_DIR}/${APP_NAME}.ino.elf" "${FIRMWARE_ELF}"
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different
                "${ARDUINO_BUILD_DIR}/${APP_NAME}.ino.bin" "${FIRMWARE_BIN}"
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different
                "${ARDUINO_BUILD_DIR}/${APP_NAME}.ino.uf2" "${FIRMWARE_UF2}"
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different
                "${ARDUINO_BUILD_DIR}/${APP_NAME}.ino.map" "${FIRMWARE_MAP}"
            VERBATIM
        )
    endif()
endfunction()

add_arduino_compile_target(firmware)
add_arduino_compile_target(firmware_debug DEBUG)
add_arduino_compile_target(firmware_upload UPLOAD)
add_arduino_compile_target(firmware_compile_db COMPILE_DB)

message(STATUS "Arduino FQBN: ${ARDUINO_FQBN}")
message(STATUS "Generated sketch: ${SKETCH_DIR}")
message(STATUS "Arduino build dir: ${ARDUINO_BUILD_DIR}")
"""


APP_CPP_TEMPLATE = """#include <JaszczurHAL.h>
#include <hal/hal_app.h>
#include <hal/hal_gpio.h>
#include <hal/hal_system.h>
#include <utils/tools_api.h>

extern "C" void app_start(void) {
    debugInit();
    setDebugPrefixWithColon("@@MODULE@@");
    hal_gpio_set_mode(HAL_LED_BUILTIN, HAL_GPIO_OUTPUT);
    hal_deb("JaszczurHAL VS Code example started");
}

extern "C" void app_task0(void) {
    static bool led_on = false;

    led_on = !led_on;
    hal_gpio_write(HAL_LED_BUILTIN, led_on);
    hal_deb("blink");
    hal_delay_ms(500u);
}
"""


HAL_PROJECT_CONFIG_TEMPLATE = """#pragma once

#define HAL_PROVIDE_APP_ENTRY
"""


TASKS_TEMPLATE = """{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Project: Build",
            "detail": "Compile @@MODULE@@ through JaszczurHAL VS Code entry",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["build", "--project", "${workspaceFolder}"],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": "$gcc"
        },
        {
            "label": "Project: Build (Debug)",
            "detail": "Debug build @@MODULE@@ through JaszczurHAL VS Code entry",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["build-debug", "--project", "${workspaceFolder}"],
            "group": "build",
            "problemMatcher": "$gcc"
        },
        {
            "label": "Project: Upload",
            "detail": "Identity-verified @@MODULE@@ serial upload",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["upload", "--project", "${workspaceFolder}"],
            "problemMatcher": "$gcc"
        },
        {
            "label": "Project: Upload (UF2 / BOOTSEL)",
            "detail": "Build @@MODULE@@ and copy UF2 to the single visible BOOTSEL drive",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["upload-uf2", "--project", "${workspaceFolder}"],
            "problemMatcher": []
        },
        {
            "label": "Project: List ports",
            "detail": "Show serial ports, identity matches, and BOOTSEL candidates",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["list-ports", "--project", "${workspaceFolder}"],
            "problemMatcher": []
        },
        {
            "label": "Project: Serial Monitor",
            "detail": "Persistent @@MODULE@@ serial monitor",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["monitor", "--project", "${workspaceFolder}", "--lock-policy", "replace-own"],
            "isBackground": true,
            "problemMatcher": []
        },
        {
            "label": "Project: Debug Probe Monitor",
            "detail": "Debug Probe monitor through JaszczurHAL VS Code entry",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["monitor-probe", "--project", "${workspaceFolder}", "--lock-policy", "replace-own"],
            "isBackground": true,
            "problemMatcher": []
        },
        {
            "label": "Project: Serial Monitor (Any)",
            "detail": "Any serial monitor through JaszczurHAL VS Code entry",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["monitor-any", "--project", "${workspaceFolder}", "--lock-policy", "wait"],
            "isBackground": true,
            "problemMatcher": []
        },
        {
            "label": "Project: Refresh IntelliSense",
            "detail": "Refresh @@MODULE@@ IntelliSense through JaszczurHAL VS Code entry",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["refresh-intellisense", "--project", "${workspaceFolder}"],
            "problemMatcher": []
        },
        {
            "label": "Project: Clean",
            "detail": "Clean @@MODULE@@ build directory",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["clean", "--project", "${workspaceFolder}"],
            "problemMatcher": []
        },
        {
            "label": "Project: Clear USB Identity",
            "detail": "Flash neutral firmware after verifying current @@USB_PRODUCT@@ identity",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["clear-identity", "--project", "${workspaceFolder}"],
            "problemMatcher": []
        },
        {
            "label": "Project: Config Dump",
            "detail": "Show resolved JaszczurHAL VS Code project configuration",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["config-dump", "--project", "${workspaceFolder}"],
            "problemMatcher": []
        }
    ]
}
"""


LAUNCH_TEMPLATE = """{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Project: Debug Firmware",
            "type": "cortex-debug",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "executable": "${workspaceFolder}/.build/firmware.elf",
            "servertype": "openocd",
            "device": "RP2040",
            "runToEntryPoint": "setup",
            "preLaunchTask": "Project: Build (Debug)"
        }
    ]
}
"""


KEYBINDINGS_TEMPLATE = """[
    {
        "key": "ctrl+shift+1",
        "command": "workbench.action.tasks.runTask",
        "args": "Project: Build"
    },
    {
        "key": "ctrl+shift+2",
        "command": "workbench.action.tasks.runTask",
        "args": "Project: Upload"
    },
    {
        "key": "ctrl+shift+3",
        "command": "workbench.action.tasks.runTask",
        "args": "Project: Serial Monitor"
    },
    {
        "key": "ctrl+shift+4",
        "command": "workbench.action.tasks.runTask",
        "args": "Project: Upload (UF2 / BOOTSEL)"
    },
    {
        "key": "ctrl+shift+5",
        "command": "workbench.action.tasks.runTask",
        "args": "Project: Debug Probe Monitor"
    },
    {
        "key": "ctrl+shift+6",
        "command": "workbench.action.tasks.runTask",
        "args": "Project: Refresh IntelliSense"
    },
    {
        "key": "ctrl+shift+7",
        "command": "workbench.action.tasks.runTask",
        "args": "Project: Clean"
    },
    {
        "key": "ctrl+shift+8",
        "command": "workbench.action.tasks.runTask",
        "args": "Project: Config Dump"
    }
]
"""


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
