#!/usr/bin/env python3
"""Generate a standalone JaszczurHAL VS Code example firmware project."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path


DEFAULT_PROJECT_NAME = "jaszczurhal-vscode-example"
DEFAULT_MODULE = "example"
DEFAULT_TARGET = "rp2040"
DEFAULT_USB_MANUFACTURER = "Jaszczur"
DEFAULT_USB_PRODUCT = "Example Project"


GENERATED_FILES = (
    ".gitignore",
    "README.md",
    "app.cpp",
    "hal_project_config.h",
    ".vscode/jaszczurhal.project.json",
    ".vscode/settings.json",
    ".vscode/tasks.json",
    ".vscode/launch.json",
    ".vscode/extensions.json",
    ".vscode/keybindings.reference.json",
)


def relpath(from_dir: Path, to_path: Path) -> str:
    return os.path.relpath(to_path.resolve(), start=from_dir.resolve()).replace(os.sep, "/")


def sanitize_module(value: str) -> str:
    module = re.sub(r"[^A-Za-z0-9_]+", "_", value.strip()).strip("_")
    if not module:
        module = DEFAULT_MODULE
    if module[0].isdigit():
        module = f"_{module}"
    return module


def identity_hint(value: str) -> str:
    hint = re.sub(r"[^A-Za-z0-9]+", "_", value.strip()).strip("_")
    return hint or DEFAULT_USB_PRODUCT


def render_template(template: str, values: dict[str, str]) -> str:
    for key, value in values.items():
        template = template.replace(f"@@{key}@@", value)
    return template


def json_text(data: dict) -> str:
    return json.dumps(data, indent=4, sort_keys=False) + "\n"


def load_target_registry(jh_root: Path) -> dict[str, dict]:
    registry_dir = jh_root / "vscode" / "targets"
    registry: dict[str, dict] = {}
    for path in sorted(registry_dir.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            raise RuntimeError(f"target descriptor must be a JSON object: {path}")
        target_id = str(data.get("id") or path.stem)
        registry[target_id] = data
    return registry


def resolve_target_board(registry: dict[str, dict], target: str, board: str | None) -> tuple[str, str]:
    if target not in registry:
        known = ", ".join(sorted(registry)) or "(none)"
        raise RuntimeError(f"unknown target '{target}'. Known targets: {known}")

    desc = registry[target]
    boards = [item for item in (desc.get("boards") or []) if isinstance(item, dict)]
    board_ids = [str(item.get("id")) for item in boards if item.get("id")]
    selected = board or desc.get("defaultBoard")
    if not selected:
        raise RuntimeError(f"target '{target}' does not define a default board; pass --board")
    selected = str(selected)
    if board_ids and selected not in board_ids:
        raise RuntimeError(
            f"unknown board '{selected}' for target '{target}'. Known boards: {', '.join(board_ids)}"
        )
    return target, selected


def board_selection_label(target: str, board: str, desc: dict, board_desc: dict) -> str:
    label = f"{target}:{board} - {board_desc.get('displayName', board)}"
    if desc.get("status") == "skeleton":
        label += " (skeleton)"
    return label


def board_selection_values(registry: dict[str, dict], selected_target: str, selected_board: str) -> tuple[str, str]:
    options: list[str] = []
    default = ""
    sorted_targets = sorted(registry.items(), key=lambda item: (item[1].get("status") == "skeleton", item[0]))
    for target, desc in sorted_targets:
        boards = [item for item in (desc.get("boards") or []) if isinstance(item, dict)]
        for board_desc in boards:
            board = board_desc.get("id")
            if not board:
                continue
            board = str(board)
            label = board_selection_label(target, board, desc, board_desc)
            options.append(label)
            if target == selected_target and board == selected_board:
                default = label
    if not options:
        raise RuntimeError("target registry has no selectable boards")
    if not default:
        default = options[0]
    return json.dumps(options, indent=16), json.dumps(default)


def ensure_writable_output(output_dir: Path, force: bool) -> None:
    if not output_dir.exists():
        return
    if not output_dir.is_dir():
        raise RuntimeError(f"output path exists and is not a directory: {output_dir}")
    if force:
        return
    try:
        next(output_dir.iterdir())
    except StopIteration:
        return
    raise RuntimeError(
        f"output directory is not empty: {output_dir}\n"
        "Use --force to overwrite files generated by this tool."
    )


def build_files(
    *,
    output_dir: Path,
    project_name: str,
    module: str,
    target: str,
    board: str | None,
    usb_manufacturer: str,
    usb_product: str,
    by_id_hint: str,
) -> dict[str, str]:
    script_path = Path(__file__).resolve()
    jh_root = script_path.parents[2]
    vscode_dir = output_dir / ".vscode"
    registry = load_target_registry(jh_root)
    target, board = resolve_target_board(registry, target, board)
    board_options_json, board_default_json = board_selection_values(registry, target, board)
    values = {
        "PROJECT_NAME": project_name,
        "MODULE": module,
        "TARGET": target,
        "BOARD": board,
        "USB_MANUFACTURER": usb_manufacturer,
        "USB_PRODUCT": usb_product,
        "BY_ID_HINT": by_id_hint,
        "JH_ROOT_REL": relpath(output_dir, jh_root),
        "JH_DISPATCHER_REL": relpath(output_dir, jh_root / "cmake" / "jh_firmware_project"),
        "JH_ENTRY_REL": relpath(output_dir, jh_root / "vscode" / "entry" / "jh-vscode"),
        "SCHEMA_REL": relpath(vscode_dir, jh_root / "vscode" / "schema" / "jh_vscode_project.schema.json"),
        "BOARD_OPTIONS_JSON": board_options_json,
        "BOARD_DEFAULT_JSON": board_default_json,
    }

    files: dict[str, str] = {
        ".gitignore": GITIGNORE_TEMPLATE,
        "README.md": render_template(README_TEMPLATE, values),
        "app.cpp": render_template(APP_CPP_TEMPLATE, values),
        "hal_project_config.h": HAL_PROJECT_CONFIG_TEMPLATE,
        ".vscode/jaszczurhal.project.json": json_text(
            {
                "$schema": values["SCHEMA_REL"],
                "project": project_name,
                "module": module,
                "toolchain": "cmake",
                "target": target,
                "board": board,
                "buildDir": "${project}/.build",
                "cmakeBuildDir": "${project}/.build/cmake",
                "cmake": {
                    "sourceDir": f"${{project}}/{values['JH_DISPATCHER_REL']}",
                    "cache": {
                        "JH_PROJECT_DIR": "${project}",
                        "JH_MODULE_NAME": module,
                    },
                },
                "identity": {
                    "enabled": True,
                    "usbManufacturer": usb_manufacturer,
                    "usbProduct": usb_product,
                    "byIdHint": by_id_hint,
                },
                "artifacts": {
                    "elf": "${buildDir}/firmware.elf",
                    "uf2": "${buildDir}/firmware.uf2",
                    "compileCommands": "${buildDir}/compile_commands_patched.json",
                },
            }
        ),
        ".vscode/settings.json": json_text(
            {
                "jaszczurhal.cliPath": "arduino-cli",
                "jaszczurhal.sketchbookPath": "",
                "jaszczurhal.buildDir": "${workspaceFolder}/.build",
                "jaszczurhal.verbose": False,
                "jaszczurhal.root": values["JH_ROOT_REL"],
                "jaszczurhal.vscodeEntry": values["JH_ENTRY_REL"],
                "C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools",
                "C_Cpp.default.compileCommands": "${workspaceFolder}/.build/compile_commands_patched.json",
                "cmake.sourceDirectory": f"${{workspaceFolder}}/{values['JH_DISPATCHER_REL']}",
                "cmake.buildDirectory": "${workspaceFolder}/.build/cmake",
            }
        ),
        ".vscode/tasks.json": render_template(TASKS_TEMPLATE, values),
        ".vscode/launch.json": render_template(LAUNCH_TEMPLATE, values),
        ".vscode/extensions.json": json_text(
            {
                "recommendations": [
                    "ms-vscode.cpptools",
                    "ms-vscode.cmake-tools",
                    "marus25.cortex-debug",
                ]
            }
        ),
        ".vscode/keybindings.reference.json": render_template(KEYBINDINGS_TEMPLATE, values),
    }
    return files


def write_files(output_dir: Path, files: dict[str, str], dry_run: bool) -> None:
    for rel, content in files.items():
        path = output_dir / rel
        if dry_run:
            print(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a standalone JaszczurHAL VS Code example firmware project."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path.cwd() / DEFAULT_PROJECT_NAME,
        help=f"Target project directory, default: ./{DEFAULT_PROJECT_NAME}",
    )
    parser.add_argument("--name", default=DEFAULT_PROJECT_NAME, help="Project name stored in the manifest.")
    parser.add_argument("--module", default=DEFAULT_MODULE, help="Firmware module/sketch name, default: example.")
    parser.add_argument("--target", default=DEFAULT_TARGET, help=f"Initial target id, default: {DEFAULT_TARGET}.")
    parser.add_argument("--board", default="", help="Initial board id; defaults to the selected target's default board.")
    parser.add_argument(
        "--usb-manufacturer",
        default=DEFAULT_USB_MANUFACTURER,
        help=f"USB manufacturer descriptor, default: {DEFAULT_USB_MANUFACTURER}.",
    )
    parser.add_argument(
        "--usb-product",
        default=DEFAULT_USB_PRODUCT,
        help=f"USB product descriptor, default: {DEFAULT_USB_PRODUCT}.",
    )
    parser.add_argument(
        "--by-id-hint",
        default="",
        help="Substring expected in /dev/serial/by-id; defaults to the USB product with spaces as underscores.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite files generated by this tool in an existing directory.",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print generated file paths without writing them.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    output_dir = args.output.expanduser().resolve()
    module = sanitize_module(args.module)
    by_id_hint = args.by_id_hint.strip() or identity_hint(args.usb_product)

    try:
        ensure_writable_output(output_dir, args.force)
        files = build_files(
            output_dir=output_dir,
            project_name=args.name.strip() or DEFAULT_PROJECT_NAME,
            module=module,
            target=args.target.strip() or DEFAULT_TARGET,
            board=args.board.strip() or None,
            usb_manufacturer=args.usb_manufacturer.strip() or DEFAULT_USB_MANUFACTURER,
            usb_product=args.usb_product.strip() or DEFAULT_USB_PRODUCT,
            by_id_hint=by_id_hint,
        )
        write_files(output_dir, files, args.dry_run)
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if not args.dry_run:
        print(f"Generated JaszczurHAL VS Code example: {output_dir}")
        print(f"Run: {relpath(output_dir, Path(__file__).resolve().parents[2] / 'vscode' / 'entry' / 'jh-vscode')} build --project {output_dir}")
    return 0


GITIGNORE_TEMPLATE = """.build/
build/
.vscode/.jh-upload-in-progress
.vscode/jaszczurhal.local.json
.vscode/c_cpp_properties.json
compile_commands.json
compile_commands_patched.json
*.elf
*.bin
*.uf2
*.map
"""


README_TEMPLATE = """# @@PROJECT_NAME@@

Standalone JaszczurHAL VS Code example project generated by
`libraries/JaszczurHAL/vscode/tools/create-vscode-example.py`.

The project demonstrates the current firmware workflow:

- The manifest points CMake at JaszczurHAL's shared firmware dispatcher.
- Target/board selection starts at `@@TARGET@@:@@BOARD@@` and can be changed
  without editing tracked files.
- `jh-vscode` owns build, debug build, upload, UF2 upload, monitor, clean, and IntelliSense refresh.
- The firmware identity is `@@USB_MANUFACTURER@@ @@USB_PRODUCT@@`.
- Application code lives in `app.cpp` and uses `app_start` / `app_task0`.

## Build

```bash
@@JH_ENTRY_REL@@ build --project "$PWD"
@@JH_ENTRY_REL@@ build-debug --project "$PWD"
@@JH_ENTRY_REL@@ refresh-intellisense --project "$PWD"
```

## Target / Board

```bash
@@JH_ENTRY_REL@@ select-board --project "$PWD" --interactive
@@JH_ENTRY_REL@@ select-board --project "$PWD" --target stm32g474 --board nucleo-g474re
@@JH_ENTRY_REL@@ config-dump --project "$PWD"
```

The selection is stored in `.vscode/jaszczurhal.local.json`, which is ignored by
the generated `.gitignore`.

## Flashing

Check visible serial ports and BOOTSEL candidates before flashing:

```bash
@@JH_ENTRY_REL@@ list-ports --project "$PWD"
```

Default serial upload is identity-guarded. After the board already runs this
example firmware, use:

```bash
@@JH_ENTRY_REL@@ upload --project "$PWD"
```

For RP2040 first flash of a blank board, either use BOOTSEL:

```bash
@@JH_ENTRY_REL@@ upload-uf2 --project "$PWD"
```

or make an explicit serial decision:

```bash
@@JH_ENTRY_REL@@ upload --project "$PWD" --port /dev/ttyACM0 --allow-unverified-port
```

The explicit-port path is intentionally manual because it can overwrite any
board connected on that port.
"""


APP_CPP_TEMPLATE = """#include <JaszczurHAL.h>
#include <hal/hal_app.h>
#include <hal/hal_gpio.h>
#include <hal/hal_system.h>
#include <utils/tools_api.h>

extern "C" void app_start(void) {
    debugInit();
    setDebugPrefixWithColon("@@MODULE@@");
    hal_gpio_set_mode(HAL_LED_BUILTIN, HAL_GPIO_OUTPUT);
    hal_deb("JaszczurHAL VS Code example started");
}

extern "C" void app_task0(void) {
    static bool led_on = false;

    led_on = !led_on;
    hal_gpio_write(HAL_LED_BUILTIN, led_on);
    hal_deb("blink");
    hal_delay_ms(500u);
}
"""


HAL_PROJECT_CONFIG_TEMPLATE = """#pragma once

#ifndef HAL_PROVIDE_APP_ENTRY
#define HAL_PROVIDE_APP_ENTRY
#endif
"""


TASKS_TEMPLATE = """{
    "version": "2.0.0",
    "inputs": [
        {
            "id": "boardSelection",
            "description": "Target/board",
            "type": "pickString",
            "options": @@BOARD_OPTIONS_JSON@@,
            "default": @@BOARD_DEFAULT_JSON@@
        }
    ],
    "tasks": [
        {
            "label": "Project: Build",
            "detail": "Compile @@MODULE@@ through JaszczurHAL VS Code entry",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["build", "--project", "${workspaceFolder}"],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": "$gcc"
        },
        {
            "label": "Project: Build (Debug)",
            "detail": "Debug build @@MODULE@@ through JaszczurHAL VS Code entry",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["build-debug", "--project", "${workspaceFolder}"],
            "group": "build",
            "problemMatcher": "$gcc"
        },
        {
            "label": "Project: Upload",
            "detail": "Upload @@MODULE@@ through the active target backend",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["upload", "--project", "${workspaceFolder}"],
            "problemMatcher": "$gcc"
        },
        {
            "label": "Project: Upload (UF2 / BOOTSEL)",
            "detail": "RP2040 only: build @@MODULE@@ and copy UF2 to the single visible BOOTSEL drive",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["upload-uf2", "--project", "${workspaceFolder}"],
            "problemMatcher": []
        },
        {
            "label": "Project: List ports",
            "detail": "Show serial ports, identity matches, and BOOTSEL candidates",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["list-ports", "--project", "${workspaceFolder}"],
            "problemMatcher": []
        },
        {
            "label": "Project: Serial Monitor",
            "detail": "Persistent @@MODULE@@ serial monitor",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["monitor", "--project", "${workspaceFolder}", "--lock-policy", "replace-own"],
            "isBackground": true,
            "problemMatcher": []
        },
        {
            "label": "Project: Debug Probe Monitor",
            "detail": "Debug Probe monitor through JaszczurHAL VS Code entry",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["monitor-probe", "--project", "${workspaceFolder}", "--lock-policy", "replace-own"],
            "isBackground": true,
            "problemMatcher": []
        },
        {
            "label": "Project: Serial Monitor (Any)",
            "detail": "Any serial monitor through JaszczurHAL VS Code entry",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["monitor-any", "--project", "${workspaceFolder}", "--lock-policy", "wait"],
            "isBackground": true,
            "problemMatcher": []
        },
        {
            "label": "Project: Refresh IntelliSense",
            "detail": "Refresh @@MODULE@@ IntelliSense through JaszczurHAL VS Code entry",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["refresh-intellisense", "--project", "${workspaceFolder}"],
            "problemMatcher": []
        },
        {
            "label": "Project: Clean",
            "detail": "Clean @@MODULE@@ build directory",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["clean", "--project", "${workspaceFolder}"],
            "problemMatcher": []
        },
        {
            "label": "Project: Clear USB Identity",
            "detail": "Flash neutral firmware after verifying current @@USB_PRODUCT@@ identity",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["clear-identity", "--project", "${workspaceFolder}"],
            "problemMatcher": []
        },
        {
            "label": "Project: Config Dump",
            "detail": "Show resolved JaszczurHAL VS Code project configuration",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["config-dump", "--project", "${workspaceFolder}"],
            "problemMatcher": []
        },
        {
            "label": "Project: Select board",
            "detail": "Interactive target/board selection",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["select-board", "--project", "${workspaceFolder}", "--interactive"],
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": true,
                "panel": "shared",
                "showReuseMessage": false,
                "clear": true
            },
            "problemMatcher": []
        },
        {
            "label": "Project: Select board (GUI)",
            "detail": "Pick target/board from the VS Code input menu",
            "type": "shell",
            "command": "${config:jaszczurhal.vscodeEntry}",
            "args": ["select-board", "--project", "${workspaceFolder}", "--selection", "${input:boardSelection}"],
            "problemMatcher": []
        }
    ]
}
"""


LAUNCH_TEMPLATE = """{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Project: Debug Firmware",
            "type": "cortex-debug",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "executable": "${workspaceFolder}/.build/firmware.elf",
            "servertype": "openocd",
            "device": "RP2040",
            "runToEntryPoint": "setup",
            "preLaunchTask": "Project: Build (Debug)"
        }
    ]
}
"""


KEYBINDINGS_TEMPLATE = """[
    {
        "key": "ctrl+shift+1",
        "command": "workbench.action.tasks.runTask",
        "args": "Project: Build"
    },
    {
        "key": "ctrl+shift+2",
        "command": "workbench.action.tasks.runTask",
        "args": "Project: Upload"
    },
    {
        "key": "ctrl+shift+3",
        "command": "workbench.action.tasks.runTask",
        "args": "Project: Serial Monitor"
    },
    {
        "key": "ctrl+shift+4",
        "command": "workbench.action.tasks.runTask",
        "args": "Project: Upload (UF2 / BOOTSEL)"
    },
    {
        "key": "ctrl+shift+5",
        "command": "workbench.action.tasks.runTask",
        "args": "Project: Debug Probe Monitor"
    },
    {
        "key": "ctrl+shift+6",
        "command": "workbench.action.tasks.runTask",
        "args": "Project: Refresh IntelliSense"
    },
    {
        "key": "ctrl+shift+7",
        "command": "workbench.action.tasks.runTask",
        "args": "Project: Clean"
    },
    {
        "key": "ctrl+shift+8",
        "command": "workbench.action.tasks.runTask",
        "args": "Project: Config Dump"
    },
    {
        "key": "ctrl+shift+alt+1",
        "command": "workbench.action.tasks.runTask",
        "args": "Project: Select board (GUI)"
    },
    {
        "key": "ctrl+shift+alt+2",
        "command": "workbench.action.tasks.runTask",
        "args": "Project: Select board"
    }
]
"""


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
